# -*- coding: utf-8 -*-
"""Insurance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QlZkG9BSj_JHeqcjidEuVj-gTmwxLvBi
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv("insurance.csv")

df.head()

df.shape

df.info()

df.describe()

df.isnull().sum()

numerical_columns = ['age','bmi','children','charges']
for col in numerical_columns:
    plt.figure(figsize=(6,4))
    sns.histplot(df[col],kde = True , bins = 30)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
    plt.tight_layout()
    plt.show()

sns.countplot(x = df['children'])

sns.countplot(x = df['sex'])

sns.countplot(x = df['smoker'])

for col in numerical_columns:
    plt.figure(figsize=(6, 4))
    sns.boxplot(x=df[col])
    plt.title(f'Boxplot of {col}')
    plt.tight_layout()
    plt.show()

plt.figure(figsize=(8, 6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.tight_layout()
plt.show()

"""# DATA Cleaning and Preprocessing"""

df_cleaned = df.copy()

df_cleaned.drop_duplicates(inplace=True)

df_cleaned.shape

print("Missing Values:\n", df_cleaned.isnull().sum())

print("\nData Types:\n", df_cleaned.dtypes)

df_cleaned['sex'].value_counts()

df_cleaned['sex'] = df_cleaned['sex'].map({'male': 0, 'female': 1})

df_cleaned['smoker'].value_counts()

df_cleaned['smoker'] = df_cleaned['smoker'].map({'no': 0, 'yes': 1})

df_cleaned.head()

df_cleaned.rename(columns={
    'sex': 'is_female',
    'smoker': 'is_smoker'
}, inplace=True)

df_cleaned = pd.get_dummies(df_cleaned, columns=['region'], drop_first=True)

df_cleaned = df_cleaned.astype(int)

"""# Feature Engineering and Extraction"""

sns.histplot(df_cleaned['bmi'])

df_cleaned['bmi_category'] = pd.cut(
    df_cleaned['bmi'],
    bins=[0, 18.5, 24.9, 29.9, float('inf')],
    labels=['Underweight', 'Normal', 'Overweight', 'Obese']
)

df_cleaned

df_cleaned = pd.get_dummies(df_cleaned, columns=['bmi_category'], drop_first=True)

df_cleaned = df_cleaned.astype(int)

"""You should scale when you are using ML models that are sensitive to the magnitude of features:

Model Type	Requires Scaling?
Logistic Regression	✅ Yes
Linear Regression	✅ Yes
KNN (K-Nearest Neighbors)	✅ Yes
SVM (Support Vector Machine)	✅ Yes
PCA	✅ Yes
Neural Networks	✅ Yes

❌ Scaling not required for:

Model Type	Why?
Decision Trees	Based on splits, not distances
Random Forest	Same — tree-based
XGBoost / LightGBM	Internally handles scaling
"""

df_cleaned.columns

from sklearn.preprocessing import StandardScaler
cols_to_scale = ['age', 'bmi', 'children']
scaler = StandardScaler()
df_cleaned[cols_to_scale] = scaler.fit_transform(df_cleaned[cols_to_scale])

df_cleaned.head()

from scipy.stats import pearsonr

# ----------------------------------
# Pearson Correlation Calculation
# ----------------------------------

# List of features to check against target
selected_features = [
    'age', 'bmi', 'children', 'is_female', 'is_smoker',
    'region_northwest', 'region_southeast', 'region_southwest',
    'bmi_category_Normal', 'bmi_category_Overweight', 'bmi_category_Obese'
]

# Calculate Pearson correlation
correlations = {
    feature: pearsonr(df_cleaned[feature], df_cleaned['charges'])[0]
    for feature in selected_features
}

# Convert to DataFrame for display
correlation_df = pd.DataFrame(list(correlations.items()), columns=['Feature', 'Pearson Correlation'])

# Show the results
correlation_df.sort_values(by='Pearson Correlation', ascending=False)

cat_features = [
    'is_female', 'is_smoker',
    'region_northwest', 'region_southeast', 'region_southwest',
    'bmi_category_Normal', 'bmi_category_Overweight', 'bmi_category_Obese'
]

from scipy.stats import chi2_contingency
import pandas as pd

# Define significance level
alpha = 0.05

# Bin the target variable
df_cleaned['charges_bin'] = pd.qcut(df_cleaned['charges'], q=4, labels=False)

# Run Chi-Square test
chi2_results = {}

for col in cat_features:
    contingency = pd.crosstab(df_cleaned[col], df_cleaned['charges_bin'])
    chi2_stat, p_val, _, _ = chi2_contingency(contingency)
    decision = 'Reject Null (Keep Feature)' if p_val < alpha else 'Accept Null (Drop Feature)'
    chi2_results[col] = {
        'chi2_statistic': chi2_stat,
        'p_value': p_val,
        'Decision': decision
    }

# Convert to DataFrame
chi2_df = pd.DataFrame(chi2_results).T
chi2_df = chi2_df.sort_values(by='p_value')
chi2_df

df_cleaned.columns

final_df = df_cleaned[['age', 'is_female', 'bmi', 'children', 'is_smoker', 'charges','region_southeast','bmi_category_Obese','region_northwest']]

final_df

from sklearn.model_selection import train_test_split

X = final_df.drop('charges', axis=1)
y = final_df['charges']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import r2_score

r2 = r2_score(y_test,y_pred)
r2
n = X_test.shape[0]
p = X_test.shape[1]
adjusted_r2 = 1 - ((1- r2) * (n-1) / (n - p - 1))
adjusted_r2



